// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhamThuHa.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230628170704_HocSinh")]
    partial class HocSinh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("PhamThuHa.Models.HocSinh", b =>
                {
                    b.Property<int?>("MaLopHoc")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiaLopHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenLopHoc")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("MaLopHoc");

                    b.ToTable("HocSinh");
                });

            modelBuilder.Entity("PhamThuHa.Models.Student", b =>
                {
                    b.Property<string>("MaStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiaChiStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStudent")
                        .HasColumnType("TEXT");

                    b.HasKey("MaStudent");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
