// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhamTrungManh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230625084824_Ađd_Colum_Student_MaLop")]
    partial class Ađd_Colum_Student_MaLop
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("PhamTrungManh.Models.LopHoc", b =>
                {
                    b.Property<int>("MaLopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaLopId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("PhamTrungManh.Models.Student", b =>
                {
                    b.Property<string>("MaStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaLop")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaStudent");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
