// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PhamTrungManh.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230622134236_Student")]
    partial class Student
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("PhamTrungManh.Models.Student", b =>
                {
                    b.Property<string>("MaStudent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaStudent");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
